apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: '{{.Values.region}}-docker.pkg.dev/{{.Values.project_id}}/{{.Values.artifactRepo}}/{{.Values.imageName}}:{{.Values.tag}}'
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: gcr-json-key
